"""
order_book.py

A minimal limit order book (LOB) matching engine with price-time priority.

Design:
- Two sides: bids (buy orders) and asks (sell orders).
- Each side is a dict[price] -> deque[Order], plus a sorted list of price levels
  maintained via the `sortedcontainers`-free approach (we just keep a sorted
  key list and update it lazily) to keep dependencies at zero.
- Price-time priority: at a given price level, orders are matched FIFO.
- Supports LIMIT orders (rest on the book if not immediately marketable) and
  MARKET orders (execute immediately against the best available liquidity,
  no resting).

This is intentionally simple and single-threaded / synchronous: call
`submit()` and get back a list of Trade objects generated by that submission.
"""

from __future__ import annotations

from collections import deque
from dataclasses import dataclass, field
from enum import Enum
from itertools import count
from typing import Deque, Dict, List, Optional


class Side(Enum):
    BUY = "BUY"
    SELL = "SELL"


class OrderType(Enum):
    LIMIT = "LIMIT"
    MARKET = "MARKET"


_order_id_counter = count(1)
_trade_id_counter = count(1)


@dataclass
class Order:
    side: Side
    price: Optional[float]   # None for market orders
    qty: float
    order_type: OrderType = OrderType.LIMIT
    order_id: int = field(default_factory=lambda: next(_order_id_counter))
    timestamp: float = 0.0   # simulation time at submission
    owner: str = "market"    # tag: e.g. "mm" for the market maker, "flow" for noise traders

    def __repr__(self) -> str:
        p = f"{self.price:.4f}" if self.price is not None else "MKT"
        return f"Order(#{self.order_id} {self.side.value} {self.qty:.2f}@{p} owner={self.owner})"


@dataclass
class Trade:
    trade_id: int
    price: float
    qty: float
    aggressor_side: Side     # the side that "took" liquidity
    resting_order_id: int
    aggressing_order_id: int
    timestamp: float
    resting_owner: str
    aggressing_owner: str


class LimitOrderBook:
    """
    A price-time-priority limit order book for a single instrument.
    """

    def __init__(self, tick_size: float = 0.01):
        self.tick_size = tick_size
        # price -> FIFO queue of resting orders at that price
        self.bids: Dict[float, Deque[Order]] = {}
        self.asks: Dict[float, Deque[Order]] = {}
        self.trades: List[Trade] = []

    # ------------------------------------------------------------------
    # Book state helpers
    # ------------------------------------------------------------------

    def best_bid(self) -> Optional[float]:
        return max(self.bids.keys()) if self.bids else None

    def best_ask(self) -> Optional[float]:
        return min(self.asks.keys()) if self.asks else None

    def mid_price(self) -> Optional[float]:
        bb, ba = self.best_bid(), self.best_ask()
        if bb is None or ba is None:
            return None
        return 0.5 * (bb + ba)

    def spread(self) -> Optional[float]:
        bb, ba = self.best_bid(), self.best_ask()
        if bb is None or ba is None:
            return None
        return ba - bb

    def depth_at(self, side: Side, price: float) -> float:
        book = self.bids if side == Side.BUY else self.asks
        return sum(o.qty for o in book.get(price, ()))

    def book_snapshot(self, levels: int = 5):
        """Return top `levels` price levels on each side as (price, qty) lists."""
        bid_prices = sorted(self.bids.keys(), reverse=True)[:levels]
        ask_prices = sorted(self.asks.keys())[:levels]
        bid_levels = [(p, sum(o.qty for o in self.bids[p])) for p in bid_prices]
        ask_levels = [(p, sum(o.qty for o in self.asks[p])) for p in ask_prices]
        return bid_levels, ask_levels

    # ------------------------------------------------------------------
    # Order submission / matching
    # ------------------------------------------------------------------

    def submit(self, order: Order) -> List[Trade]:
        """
        Submit an order to the book. Matches against the opposite side first
        (price-time priority), then rests any unfilled remainder on the book
        (limit orders only; market orders never rest).
        """
        if order.order_type == OrderType.MARKET:
            fills = self._match(order)
            # Any unfilled market-order quantity is simply dropped (no liquidity).
            return fills

        # Limit order: match what's marketable, rest the remainder.
        fills = self._match(order)
        if order.qty > 1e-12:
            book = self.bids if order.side == Side.BUY else self.asks
            book.setdefault(order.price, deque()).append(order)
        return fills

    def cancel(self, order_id: int) -> bool:
        """Remove a resting order by id. Returns True if found and removed."""
        for book in (self.bids, self.asks):
            for price, dq in list(book.items()):
                for o in list(dq):
                    if o.order_id == order_id:
                        dq.remove(o)
                        if not dq:
                            del book[price]
                        return True
        return False

    def _match(self, incoming: Order) -> List[Trade]:
        fills: List[Trade] = []
        opposite = self.asks if incoming.side == Side.BUY else self.bids

        def is_marketable(level_price: float) -> bool:
            if incoming.order_type == OrderType.MARKET:
                return True
            if incoming.side == Side.BUY:
                return level_price <= incoming.price
            else:
                return level_price >= incoming.price

        while incoming.qty > 1e-12 and opposite:
            best_price = min(opposite.keys()) if incoming.side == Side.BUY else max(opposite.keys())
            if not is_marketable(best_price):
                break

            queue = opposite[best_price]
            while incoming.qty > 1e-12 and queue:
                resting = queue[0]
                traded_qty = min(incoming.qty, resting.qty)

                trade = Trade(
                    trade_id=next(_trade_id_counter),
                    price=best_price,
                    qty=traded_qty,
                    aggressor_side=incoming.side,
                    resting_order_id=resting.order_id,
                    aggressing_order_id=incoming.order_id,
                    timestamp=incoming.timestamp,
                    resting_owner=resting.owner,
                    aggressing_owner=incoming.owner,
                )
                fills.append(trade)
                self.trades.append(trade)

                incoming.qty -= traded_qty
                resting.qty -= traded_qty

                if resting.qty <= 1e-12:
                    queue.popleft()

            if not queue:
                del opposite[best_price]

        return fills
